version: '3.8'

services:
  app:
    build: . # Dockerfileがある場所を指定
    container_name: tm-app-server
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app"
    tty: true
    depends_on:
      - db # dbコンテナが起動してからappコンテナを起動させる
  db:
    image: mysql:8.3
    platform: linux/amd64
    container_name: tm-app-server-db
    environment:
      MYSQL_DATABASE: tm_app_server_db
      MYSQL_ROOT_PASSWORD: password
    # command: >
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_general_ci
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-volume:
