// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type DeleteTodoInput struct {
	ID string `json:"id"`
}

type FetchTodoInput struct {
	ID string `json:"id"`
}

type FetchUserInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateTodoInput struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
